### PR TITLE
Update toHaveClass/toHaveTextContent method signatures

### PR DESCRIPTION
**Pull request by wyze**
- Remove toHaveClassMany and use variadic argument in toHaveClass
- Remove toHaveTextContentRe and use variadic argument in toHaveTextContent

### CODE REVIEW

**Comment by wyze** [comment]
Curious @jihchi if you know how to get something like this to work? I tried `[@bs.unwrap]` but I'm not sure if that works outside of `external`.

**Comment by jihchi** [comment]
I believe that `[@bs.unwrap]` works with `external` only.

**Comment by jihchi** [comment]
maybe we could unwrap variant before invoke underlaying function? similar to `toHaveClass ` function. for example:

https://github.com/wyze/bs-jest-dom/blob/0127009c1626ebef4c39aca565af1af1fa625953/src/JestDom.re#L146-L149

```re
let toHaveTextContent = (text, ~options=?, expected) =>
  HaveTextContent(
    mapMod(
      exp => (
        exp,
        switch (text) {
        | `Str(s) => s
        | `Lst(lst) => lst->joinList
        },
        options,
      ),
      expected,
    ),
  )
  ->affirm
  ->toJestAssertion;

```

**Comment by wyze** [comment]
@jihchi The exposed function still accepts the variadic argument, but the internals need to be split still. I guess this will work for now!

**Pull request merged**
